development:
  max_threads: 5
  poll_interval: 0.5
  throttles:
    summarization:
      queue: summarization
      limit: 1
      period: 10

production:
  max_threads: 10
  poll_interval: 1
  throttles:
    summarization:
      queue: summarization
      limit: 1
      period: 10
